# Generated by Django 2.2.1 on 2019-05-17 14:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('tramit', models.BooleanField(default=False)),
                ('validada', models.BooleanField(default=False)),
                ('id_usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuari.Usuari')),
            ],
        ),
    ]
