# Generated by Django 2.2.1 on 2019-05-17 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.IntegerField(verbose_name='numero de telefon de contacte')),
                ('pais', models.CharField(choices=[('ESP', 'Espana'), ('USA', 'United States'), ('GB', 'United Kingdom'), ('GER', 'Deutschland'), ('NL', 'Netherlands'), ('FR', 'France'), ('BEL', 'Belgium'), ('ITA', 'Italia')], default='ESP', max_length=3)),
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
