# Generated by Django 2.2.1 on 2019-05-09 15:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nom_user', models.CharField(max_length=30, verbose_name='nom usuari')),
                ('cognoms_user', models.CharField(max_length=60, verbose_name='nom usuari')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('pais', models.CharField(choices=[('ESP', 'Espana'), ('USA', 'United States'), ('GB', 'United Kingdom'), ('GER', 'Deutschland'), ('NL', 'Netherlands'), ('FR', 'France'), ('BEL', 'Belgium'), ('ITA', 'Italia')], default='ESP', max_length=3)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
