# Generated by Django 2.2.1 on 2019-05-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefon',
            field=models.CharField(default=0, max_length=9, verbose_name='numero de telefon de contacte'),
            preserve_default=False,
        ),
    ]
