# Generated by Django 2.2.1 on 2019-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuari', '0002_user_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cognoms_user',
            field=models.CharField(max_length=60, verbose_name='cognom usuari'),
        ),
    ]
